package cz.artique.shared.utils;

import com.google.appengine.api.datastore.Key;

/**
 * Marker interface for model classes that have their {@link Key} generated by
 * {@link GenKey} instead of using default auto-increment.
 * 
 * @author Adam Juraszek
 * 
 */
public interface GenKey {

	/**
	 * @return unique name which represents this object
	 */
	String getKeyName();
}
