package cz.artique.shared.model.shortcut;

public enum ShortcutAction {
	REFRESH,
	MARK_READ_ALL,
	TOGGLE_COLLAPSED,
	NEXT_ITEM,
	PREVIOUS_ITEM,
	OPEN_ORIGINAL,
	ADD_LABEL,
	CLEAR_FILTER,
	TOTAL_CLEAR_FILTER,
	ADD_NEW_ITEMS,
	ADD_MANUAL_ITEM;
}
