package cz.artique.shared.model.item;

import java.io.Serializable;
import java.util.Date;

import org.slim3.datastore.Attribute;
import org.slim3.datastore.Model;

import cz.artique.server.crawler.XMLCrawler;
import cz.artique.shared.model.source.Source;
import cz.artique.shared.model.source.XMLSource;

/**
 * Type of {@link Item} provided by {@link XMLSource} and generated by
 * {@link XMLCrawler}. {@link ArticleItem} extends general {@link Item}; adds
 * following attributes:
 * <ul>
 * <li>Author - author of article taken from RSS/Atom
 * <li>Published - time-stamp taken from RSS/Atom specifying when the article
 * was published
 * </ul>
 * 
 * @author Adam Juraszek
 * 
 */
@Model(schemaVersion = 1)
public class ArticleItem extends Item implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * Author of article
	 */
	@Attribute(unindexed = true)
	private String author;

	/**
	 * Date of publish
	 */
	@Attribute(unindexed = true)
	private Date published;

	/**
	 * Default constructor for slim3 framework.
	 */
	public ArticleItem() {}

	/**
	 * Constructor just calling constructor of super-type:
	 * {@link Item#Item(Source)}.
	 * 
	 * @param source
	 */
	public ArticleItem(Source source) {
		super(source);
	}

	/**
	 * @return author or null if it's not known
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * @param author
	 *            author or null if it's not known
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * @return date the article was published, null if it's not known
	 */
	public Date getPublished() {
		return published;
	}

	/**
	 * @param published
	 *            date the article was published, null if it's not known
	 */
	public void setPublished(Date published) {
		this.published = published;
	}

}
