package cz.artique.shared.model.item;

import java.io.Serializable;

import org.slim3.datastore.Model;

import cz.artique.server.crawler.WebSiteCrawler;
import cz.artique.shared.model.source.Source;
import cz.artique.shared.model.source.WebSiteSource;

/**
 * Type of {@link Item} provided by {@link WebSiteSource} and generated by
 * {@link WebSiteCrawler}. {@link LinkItem} extends general {@link Item}; does
 * not add any attributes.
 * 
 * @author Adam Juraszek
 * 
 */
@Model(schemaVersion = 1)
public class LinkItem extends Item implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * Default constructor for slim3 framework.
	 */
	public LinkItem() {}

	/**
	 * Constructor just calling constructor of super-type:
	 * {@link Item#Item(Source)}.
	 * 
	 * @param source
	 */
	public LinkItem(Source source) {
		super(source);
	}
}
