package cz.artique.shared.validation;

public enum IssueType {
	INVALID_URL,
	UNREACHABLE_URL,
	PROPERTY_EMPTY,
	PROPERTY_TOO_LONG,
	INVALID_SELECTOR,
	INVALID_LABEL,
	ALREADY_EXISTS,
	SECURITY_BREACH,
	WRONG_TYPE,
	UNKNOWN;
}
